config/routes.rb
Rails.application.routes.draw do
  # get 'shippingdetails/create'
  # get 'payment/create'
  # get 'checkouts/new'
  # get 'checkouts/create'
  # get 'shippingdetails', to: "shippingdetails#new"

  # get 'listings/index'
  # get 'listings/create'
  # get 'listings/new'
  # get 'listings/edit'
  # get 'listings/show'
  # get 'listings/update'
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :listings
  # get '/listings?search=:value', to: 'listings#search'
  # get '/listings?category=:value', to: "listings#category"

  post '/listings/:id/checkout', to: 'checkouts#add_shipping_detail', as: :checkout_add_shippingdetail

  get '/listings/:id/checkout', to: 'checkouts#new', as: :checkout
  post '/listings/:id/checkout', to: 'checkouts#create', as: :checkout_create

  resources :shippingdetails, only: [:create, :destroy]
  resources :orders, only: [:index, :show, :create]

  get '/orders/:id/cancel', to: "orders#cancel", as: :order_cancel # check this route when free
  get '/seller/:id', to: "listings#seller_all", as: :seller
  get '/seller/:id/shipping', to: "listings#seller_ship", as: :seller_ship # to-be-shipped route

  mount StripeEvent::Engine, at: '/stripe-webhooks'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/checkout.rb
class Checkout < ApplicationRecord
  has_one :payment
  belongs_to :listing
  belongs_to :buyer, class_name: "User"
  monetize :amount_cents


  def seller
    listing.seller
  end
end

app/models/listing.rb
class Listing < ApplicationRecord
  has_many :checkout
  belongs_to :seller, class_name: "User"

  monetize :price_cents

  has_many_attached :photos
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :listing
  monetize :amount_cents

end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :checkout
end

app/models/shippingdetail.rb
class Shippingdetail < ApplicationRecord
end

app/models/transaction.rb
class Checkout < ApplicationRecord
  has_one :payment
  belongs_to :listing
  belongs_to :buyer, class_name: "User"

  def seller
    listing.seller
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :checkouts, class_name: "Checkouts", foreign_key: "buyer_id"
  has_many :listings, class_name: "Listing", foreign_key: "seller_id"
  has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/checkouts_controller.rb
class CheckoutsController < ApplicationController
  def new
    @listing = Listing.find(params[:id])
    # @checkout = Checkout.new
    # @payment = Payment.new
    @newshippingdetail = Shippingdetail.new
    @shippingdetails = Shippingdetail.where("user_id = #{current_user.id}")
  end

  def add_shipping_detail
    @listing = Listing.find(params[:id])
    @newshippingdetail = Shippingdetail.find(params[:shipping_id])
    @shippingdetails = Shippingdetail.where("user_id = #{current_user.id}")
    render :new
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:edit, :show, :update, :destroy]
  # before_action :set_all_listings, only: [:index, :show]

  def index
    # needed for page#home
  end

  def create
    @listing = Listing.new(listing_params)
    @listing.availability = true
    @listing.seller = current_user
    if @listing.save
      redirect_to seller_path(current_user)
    else
      render :new
    end
  end

  def new
    @listing = Listing.new
  end

  def edit
    # needed
  end

  def show
    @listings_same_seller = @listing.seller.listings # to show listings from same seller
    @listings_same_seller = @listings_same_seller.reject { |ele| ele.id == params[:id].to_i }.sample(3)
  end

  def update
    @listing.availability = true
    @listing.seller = current_user
    if @listing.update(listing_params)
      redirect_to listing_path(@listing)
    else
      render :new
    end
  end

  def destroy
    @listing.destroy
    redirect_to seller_path(current_user)
  end

  def seller_all
    all_query
    @seller = User.find(params[:id])
    @listings = Listing.where("seller_id = #{params[:id]}")

    search_check
  end

  def seller_ship
    all_query
    @seller = User.find(params[:id])
    @listings = Listing.where("seller_id = #{params[:id]} AND availability = false")

    search_check
  end

  def category
    @listings = Listing.filter(params[:value])
  end

  private

  def set_listing
    @listing = Listing.find(params[:id])
  end

  def listing_params
    params.require(:listing).permit(:brand, :sneaker_model_name, :size, :price, :condition, :gender, photos: [])
  end

  def search_check
    if params[:query].present?
      @listings = @listings.where("brand ILIKE ?", "%#{params[:query]}%")
    end
  end

  def all_query
    @query = params[:query]
    @size = [params[:size_type], params[:size]].join(' ')
    @gender = params[:gender]
    @price_range = [params[:price_more_than], params[:price_less_than]].join(' – ')
  end
  # def set_all_listings
  #   @empty_listing = Listing.new
  # end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def create
    listing = Listing.find(params[:id])
    order = Order.create!(listing: listing, sneaker_sku: listing.sneaker_model_name, amount: listing.price, state: 'pending', user: current_user)

    if order.save
      session = Stripe::Checkout::Session.create(
        payment_method_types: ['card'],
        customer_email: current_user.email,
        mode: 'payment',
        line_items: [{
          quantity: 1,
          price_data: {
            currency: 'sgd',
            unit_amount: listing.price_cents,
            product_data: {
              name: listing.sneaker_model_name
            }
          }
        }],
        success_url: order_url(order),
        cancel_url: order_cancel_url(order)
      )
      order.update(checkout_session_id: session.id)
      redirect_to session.url
    else
      redirect_to "checkouts/new"
    end
  end

  def cancel
    @order = current_user.orders.find(params[:id])
    @order.state = "cancelled"
    @order.save
  end

  def show
    @order = current_user.orders.find(params[:id])
  end

  def index
    @orders = current_user.orders
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  include Pagy::Backend

  skip_before_action :authenticate_user!, only: :home
  def home
    all_query
    @listings = Listing.all
    search_check
    @pagy, @records = pagy(@listings)
    # binding.pry
    render 'listings/index'
  end

  private

  def all_query
    @query = params[:query]
    @size = [params[:size_type], params[:size]].join(' ')
    @gender = params[:gender]
    @price_range = [params[:price_more_than], params[:price_less_than]].join(' – ')
  end

  def search_check
    if @query
      query = "brand @@ :query OR sneaker_model_name @@ :query"
      @listings = @listings.where(query, query: "%#{@query}%")
    end
    # if params[:size]
    #   query = "size @@ :query"
    #   @listings = @listings.where(query, query: "%#{@size}%")
    # end
  end
end

app/controllers/payment_controller.rb
class PaymentController < ApplicationController
  def create

    # if @payment.save
    #   render "checkouts/create"
    # else
    #   render "checkouts/new"
    # end
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def new
    @order = current_user.orders.where(state: 'pending').find(params[:order_id])
  end
end

app/controllers/shippingdetails_controller.rb
class ShippingdetailsController < ApplicationController

  def create
    @shippingdetail = Shippingdetail.new(shipping_params)
    @shippingdetail.save
    @listing = Listing.find(params.require(:shippingdetail).permit(:listing_id)[:listing_id])
    @newshippingdetail = Shippingdetail.new
    redirect_to checkout_path(@listing)
  end

  def destroy
    Shippingdetail.destroy(params[:id])
    redirect_back fallback_location: root_path
  end

  private

  def shipping_params
    params.require(:shippingdetail).permit(:firstname, :lastname, :contact, :address, :city, :country, :postal, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/views/checkouts/new.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-lg-8 col-md-12">
      <div class="border">
        <div>
          <h2 class="px-5 py-3">Checkout</h2>
          <% unless @shippingdetails.nil? %>
            <%= render @shippingdetails %>
          <% else %>
            <p>There is no existing address</p>
          <% end %>
        </div>
        <div class='px-5 py-4'>
          <%= render "shippingdetails/newshippingdetail", newshippingdetail: @newshippingdetail, listing: @listing %>
        </div>
      </div>
    </div>
    <div class="position-relative">
      <div id='checkout' class="position-fixed col-4">
        <%= render "shared/checkoutitem", listing: @listing %>
        <div>
          <%= form_tag orders_path do %>
            <%= hidden_field_tag 'id', @listing.id %>
            <%= submit_tag 'Proceed to payment', class: 'btn btn-primary btn-block mt-4' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShoozApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
  <%= render 'shared/footer' %>
</html>

app/views/listings/_listing.html.erb
<div class="col-12 col-md-6 col-lg-4">
  <div class="card my-3">

    <%= link_to listing_path(listing), class: "text-decoration-none" do %>

      <% if listing.photos.first %>
        <div class="img-holder">
          <%= cl_image_tag listing.photos.first.key, crop: :scale, class: "img-fluid" %>
        </div>
      <% else %>
        <img src="https://source.unsplash.com/200x200/?sneaker" class="card-img-top img-holder" alt="sneaker image">
      <% end %>

      <% if user_signed_in? %>
        <% if current_user.id == listing.seller_id %>
          <div class="your-listing-tag top-left">Your listing</div>
        <% end %>
      <% end %>

      <div class="card-body">
        <h3 class="card-title"><%= listing.brand.capitalize %> <%= listing.sneaker_model_name.capitalize %></h3>

        <div class="card-text d-flex justify-content-between align-items-end">
          <p><%= listing.size %><br><%= listing.gender.capitalize %></p>
          <p><%= humanized_money_with_symbol(listing.price) %></p>
        </div>

        <%= link_to "View", listing_path(listing), class: "btn btn-primary btn-block" %>
      </div>

    <% end %>

  </div>
</div>

app/views/listings/_query.html.erb
<div class="pt-4">
  <% if @query != "" %>
    <h1 class="text-center ">"<%= @query %>"</h1>
  <% end %>
  <div class="text-center">
    <p>
      <% if params[:size] != "" %>
        <%= @size %>&nbsp;&nbsp;
      <% end %>
      <% if @gender != "" %>
        <%= @gender %>&nbsp;&nbsp;
      <% end %>
      <% if params[:price_more_than] != "" || params[:price_less_than] != "" %>
        SGD <%= @price_range %>
      <% end %>
    </p>

    <p>in: "<%= page %>"</p>
  </div>
  <hr>
</div>

app/views/listings/edit.html.erb
<div class="container">

  <div class="row">
    <div class="col-12 col-md-6">
      <div class="py-5">
        <% @listing.photos.each do |photo| %>
          <%= cl_image_tag photo.key, height: 400, width: 400, crop: :fill %>
        <% end %>
      </div>
    </div>

    <div class="col-12 col-md-6">
      <div class="pt-5 d-flex w-100">
        <div class="flex-grow-1">
          <%= simple_form_for @listing do |f| %>
            <%= f.input :sneaker_model_name %>
            <%= f.input :brand %>
            <div class="d-flex">
              <%= f.input :gender, collection: ['Male', 'Female', 'Unisex'] %>
              <%= f.input :size, placeholder: 'e.g. UK 8.5' %>
            </div>
            <%= f.input :condition, collection: ['Brand New', 'Like new', 'Used'] %>
            <%= f.input :price, placeholder: 'SGD' %>

            <%= f.button :submit, class: 'btn btn-primary btn-block mb-3' %>
          <% end %>
          <%= link_to 'Delete listing', listing_path(@listing), method: :delete, class: 'btn btn-outline-primary btn-block' %>
        </div>

        <div>
          <%= link_to listing_path(@listing), class: 'btn' do %>
            <i class="fas fa-times"></i>
          <% end %>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/listings/index.html.erb
<div class="banner mb-4">
</div>

<div class="container">
  <% if @query %>
    <%= render 'query' %>
  <% end %>

  <div class="row">
    <% if @listings.empty? %>
      <p class="pl-4"><em>0 results found</em></p>
    <% else %>
      <%= render @records %>
    <% end %>
  </div>

  <div class="d-flex justify-content-center">
    <%= render partial: 'pagy/bootstrap_nav', locals: {pagy: @pagy} %>
  </div>
</div>

app/views/listings/new.html.erb
<div class="container">
  <div class="d-flex justify-content-between my-4">
    <h1>Create new listing</h1>
    <%= link_to :back do %>
      <i class="fas fa-times btn-lg"></i>
    <% end %>
  </div>

  <%= simple_form_for @listing do |f| %>
    <%= f.input :photos, as: :file, input_html: { multiple: true } %>
    <%= f.input :sneaker_model_name %>
    <%= f.input :brand %>
    <div class="d-flex">
      <%= f.input :gender, collection: ['Male', 'Female', 'Unisex'] %>
      <%= f.input :size, placeholder: 'e.g. UK 8.5' %>
    </div>
    <%= f.input :condition, collection: ['Brand New', 'Like new', 'Used'] %>
    <%= f.input :price, placeholder: 'SGD' %>

    <%= f.button :submit, class: 'btn btn-primary btn-block' %>
  <% end %>
</div>

app/views/listings/seller_all.html.erb
<div class="container">
  <% if @seller == current_user %>
    <% if @query %>
      <%= render 'query', page: 'Listed' %>
    <% end %>

    <div class="d-flex justify-content-between pt-4">
      <div>
        <%= link_to 'Listed', seller_path(current_user), class: 'tab-active mr-3' %>

        <%= link_to 'To be shipped', seller_ship_path(current_user) %>
      </div>

      <%= link_to new_listing_path, class: "btn btn-primary"  do %>
        <i class="fas fa-plus pr-2"></i>Create listing
      <% end %>
    </div>

  <% else %>
    <h1 class="pt-4"><%= @seller.email %> listings</h1>
  <% end %>

  <% if @seller == current_user && @listings.empty? %>
    <p class="py-4"><em>You have 0 listings found</em></p>
  <% elsif @listings.empty? %>
    <p class="py-4"><em>0 listings found</em></p>
  <% else %>
    <div class="row">
      <%= render @listings %>
    </div>
  <% end %>
</div>

app/views/listings/seller_ship.html.erb
<div class="container">
  <% if @query %>
    <%= render 'query', page: 'To-be-shipped' %>
  <% end %>

  <div class="d-flex justify-content-between pt-4">

    <div>
      <%= link_to 'Listed', seller_path(current_user), class: 'mr-3' %>
      <%= link_to 'To be shipped', seller_ship_path(current_user), class: 'tab-active' %>
    </div>

    <%= link_to new_listing_path, class: "btn btn-primary"  do %>
      <i class="fas fa-plus pr-2"></i>Create listing
    <% end %>

  </div>

  <% if @seller == current_user && @listings.empty? %>
    <p class="py-4"><em>You have 0 listings that require shipping</em></p>
  <% end %>

  <div class="row">
    <%= render @listings %>
  </div>
</div>

app/views/listings/show.html.erb
<div class="container">
  <div class="row">

    <div class="col-12 col-md-6">
      <div class="py-5">
        <% if @listing.photos.first %>
          <% @listing.photos.each do |photo| %>
            <div class="img-holder">
              <%= cl_image_tag photo.key, crop: :scale, class: "img-fluid" %>
            </div>
          <% end %>
        <% else %>
          <img src="https://source.unsplash.com/200x200/?sneaker" class="card-img-top" alt="sneaker image">
        <% end %>
      </div>
    </div>

    <div class="col-12 col-md-6">
      <div class="d-flex justify-content-between pt-5">
        <div>
          <h1><%= @listing.brand.capitalize %> <%= @listing.sneaker_model_name.capitalize %></h1>
          <h4 class='my-2'><%= humanized_money_with_symbol(@listing.price) %></h4>

          <% if current_user.id == @listing.seller_id %>
            <div class="your-listing-tag">Your listing</div>
          <% end %>
        </div>

        <% if current_user == @listing.seller %>
          <%= link_to edit_listing_path(@listing) do %>
            <i class="far fa-edit"></i>
          <% end %>
        <% end %>
      </div>

      <table class="table table-white table-sm align-middle text-center my-5">
        <thead>
          <tr>
            <th scope="col">Size</th>
            <th scope="col">Gender</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= @listing.size %></td>
            <td><%= @listing.gender.capitalize %></td>
          </tr>
        </tbody>
      </table>

      <div class="mb-5 px-3">
        <p class='my-0'><strong>Condition: </strong><%= @listing.condition.capitalize %></p>
        <p><strong>Est. Delivery Time: </strong> <%= rand(1..10) %> days</p>
      </div>
      <%= link_to "Order now", checkout_path, id: "buy-btn", class: 'btn btn-block btn-primary' %>
    </div>
  </div>

  <div class="d-flex justify-content-between mt-4 align-items-center">
    <h2>More from this seller</h2>
      <%= link_to 'View more', seller_path(@listing.seller), class: 'btn btn-outline-primary' %>
    </div>
  <hr>

  <div class="row">
    <%= render @listings_same_seller %>
  </div>
</div>

app/views/listings/update.html.erb
<h1>Listings#update</h1>
<p>Find me in app/views/listings/update.html.erb</p>

app/views/orders/_order.html.erb
<div class="row border mt-3">
  <div class="col-8">
    <div class="px-5 py-3">
      <h3>Order #<%= order.id %> <small><span class="badge badge-primary"><%= order.state %></span></small></h3>
      <p>Estimated delivery in <strong>2 business days</strong></p>
      <%= link_to "View listing", listing_path(order.listing), class: "btn btn-primary" %>
    </div>
  </div>
  <div class="col-4">
    <table class="table my-3">
      <tbody>
        <tr>
          <th scope="row">Item: </th>
          <td class='text-right'><%= order.listing.sneaker_model_name %></td>
        </tr>
        <tr>
          <th scope="row">Brand: </th>
          <td class='text-right'><%= order.listing.brand %></td>
        </tr>
        <tr>
          <th scope="row">Size: </th>
          <td class='text-right'><%= order.listing.size %></td>
        </tr>
        <tr>
          <th scope="row">Price </th>
          <td class='text-right'><%= humanized_money_with_symbol(order.listing.price) %></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

app/views/orders/cancel.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-8">
      <div class="border px-5">
        <div class="py-3">
          <h2>Checkout canceled</h2>
          <p>Need to make any changes to your order?</p>
          <%= link_to "Return to checkout page", checkout_path(@order.listing), class: "btn btn-primary" %>
        </div>
      </div>
    </div>
    <div>
      <div class="col-4">
        <%= render "shared/checkoutitem", listing: @order.listing %>
      </div>
    </div>
  </div>
</div>

app/views/orders/fail.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-8">
      <div class="border px-5">
        <div class="py-3">
          <h2>Checkout canceled</h2>
          <p>Need to make any changes to your order?</p>
          <%= link_to "Return to checkout page", checkout_path(@order.listing), class: "btn btn-primary" %>
        </div>
      </div>
    </div>
    <div class="position-relative">
      <div class="position-fixed col-4">
        <%= render "shared/checkoutitem", listing: @order.listing %>
      </div>
    </div>
  </div>
</div>

app/views/orders/index.html.erb
<div class="container mt-3">
<h2>My orders</h2>

<% unless @orders.empty? %>
  <%= render @orders %>
<% end %>

</div>

app/views/orders/show.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-8">
      <div class="border px-5">
        <div class="py-3">
          <h2>Order #<%= @order.id %> <small><span class="badge badge-primary"><%= @order.state %></span></small></h2>
          <p>Thank you so much for your purchase.</p>
          <p>Estimated delivery in <strong>2 business days</strong></p>
          <%= link_to "Return to shopping", root_path, class: "btn btn-primary" %>
        </div>
      </div>
    </div>
    <div>
      <div class="col-4">
        <%= render "shared/checkoutitem", listing: @order.listing %>
      </div>
    </div>
  </div>
</div>

app/views/payments/create.html.erb
<h1>Payment#create</h1>
<p>Find me in app/views/payment/create.html.erb</p>

app/views/shared/_footer.html.erb
<footer class="bg-primary pt-4">
  <div class="container footer">
    <%= link_to "/", class: "align-self-start footer-logo" do %>
      <%= image_tag "logo.png", class: 'pb-2' %>
    <% end %>

    <div class="row">

      <div class="col-12 col-md-2">
        <div class="d-flex flex-column mb-4">
          <span class="footer-title mb-3">Account</span>
          <%= link_to 'Login', root_path %>
          <%= link_to 'Sign up', orders_path %>
        </div>
      </div>

      <div class="col-12 col-md-2">
        <div class="d-flex flex-column mb-4">
          <span class="footer-title mb-3">Buy</span>
          <%= link_to 'All listings', root_path %>
          <%= link_to 'Purchases', orders_path %>
        </div>
      </div>

      <div class="col-12 col-md-2">
        <div class="d-flex flex-column mb-4">
          <span class="footer-title mb-3">Sell</span>
          <%= link_to 'My listings', root_path %>
          <%= link_to 'To be shipped', root_path %>
          <%= link_to 'Create listing', new_listing_path %>
        </div>
      </div>

      <div class="col-12 col-md-6">
        <span class="footer-title">Receive discounts, promotions, and more.</span>
        <%= form_with url: request.path, method: :get, class: 'mt-3' do |f| %>

          <%= f.text_field :email, placeholder: 'hello@gmail.com', class: 'input-l py-1 px-3' %>
          <button type="submit" class="input-r p-1 footer-btn">
            <i class="fas fa-chevron-right px-1"></i>
          </button>

        <% end %>
      </div>

    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-dark navbar-lewagon">

  <%= link_to "/", class: "navbar-brand align-self-start" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <% if @listings %>
    <div class="w-50 px-3">
      <%= form_with url: request.path, class: "text-light", method: :get do |f| %>

        <div class="search-bar">
          <button type="submit" class="input-l">
            <i class="fas fa-search"></i>
          </button>
          <%= f.text_field :query, class: "search-text input-r mr-5", placeholder: "Find shoe",
          data: { toggle: "collapse", target: "#search-collapse"}
          %>
        </div>

        <div class="collapse block" id="search-collapse">
          <div class="d-flex flex-wrap">

            <div class="d-flex align-items-center pt-1">
              <%= f.label :size, 'Size', class: 'label pr-2' %>
              <div class="input-box mr-4">
                <%= f.select :size_type, ['UK', 'US'], class: "text-center" %>
                <%= f.number_field :size , in: (3.0..11.0), step: 0.5, class: "text-center"%>
              </div>
            </div>

            <div class="d-flex align-items-center pt-1">
              <%= f.label :gender, 'Gender', class: 'label pr-2 text-center' %>
              <div class="input-box mr-4">
                <%= f.select :gender, ['', 'Unisex', 'Male', 'Female'], class: "text-center" %>
              </div>
            </div>

            <div class="d-flex align-items-center pt-1">
              <%= f.label :price_less_than, 'Price range', class: 'label pr-2 text-center' %>
              <div class="input-box mr-4">
                <%= f.number_field :price_more_than, in: (1..99999), class: "text-center" %> –
                <%= f.number_field :price_less_than, in: (1..99999), class: "text-center" %>
              </div>
            </div>

          </div>
        </div>

      <% end %>
    </div>
  <% end %>

  <% if user_signed_in? %>
    <div class="nav-item dropdown text-white text-right px-3 align-self-start mt-2">
      <div class="dropdown-toggle pointer" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="far fa-user pr-2">
        </i>
        My Account
        <% #, id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
      </div>

      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
        <%= link_to "My purchase", orders_path, class: "dropdown-item" %>
        <%= link_to "My listings", seller_path(current_user), class: "dropdown-item" %>
        <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
      </div>
    </div>
  <% else %>
    <div class="nav-item text-right px-3 align-self-start mt-2">
      <%= link_to "Login/Sign up", new_user_session_path, class: "nav-link", class: "text-white text-decoration-none" %>
    </div>
  <% end %>
</div>

app/views/shippingdetails/_shippingdetail.html.erb
<div class='border-top border-bottom'>
  <div class="d-flex justify-content-between px-5 py-2">

    <div>
      <p class='m-0'>First name: <%= shippingdetail.firstname %></p>
      <p class='m-0'>Last name: <%= shippingdetail.lastname %></p>
      <p class='m-0'>Contact Number: <%= shippingdetail.contact %></p>
      <p class='m-0'>Address: <%= shippingdetail.address %></p>
      <p class='m-0'>City: <%= shippingdetail.city %></p>
      <p class='m-0'>Country: <%= shippingdetail.country %></p>
      <p class='m-0'>Postal Code:<%= shippingdetail.postal %></p>
    </div>

    <div class="d-flex flex-column justify-content-center">
      <form action="<%= checkout_add_shippingdetail_path(@listing) %>" method="post">
        <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
        <input type="hidden" name="shipping_id" value="<%= shippingdetail.id %>">
        <input type="submit" value="Use shipping details", class='btn btn-primary'>
      </form>

      <%= link_to 'Delete', shippingdetail_path(shippingdetail), method: :delete, class: "btn btn-info mt-3" %>

    </div>
  </div>
</div>